name: Install nodejs

on: workflow_dispatch

jobs:
  node-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code so that is available on the server
        uses: action/checkout@v4
      - name: Install nodejs
        uses: action/setup-node@v4
        with:
          node-version: 20
      - name: Check version
        run: node --version
